// Canonical math topics and helpful keywords used for deterministic validation.
// Keep this file authoritative and import it from both backend services and, if desired,
// expose it to the frontend so the client and server share the same list.

export const allowedTopics = [
  "algebra",
  "linear algebra",
  "pre-algebra",
  "geometry",
  "trigonometry",
  "calculus",
  "differential calculus",
  "integral calculus",
  "multivariable calculus",
  "differential equations",
  "probability",
  "statistics",
  "combinatorics",
  "number theory",
  "discrete mathematics",
  "optimization",
  "real analysis",
  "complex analysis",
  "mathematical logic",
  "set theory",
  "graph theory",
  "matrix algebra",
  "vectors",
  "measure theory",
  "topology",
  "linear programming",
  "numerical analysis",
];

export const mathKeywords = [
  "algebra",
  "geometry",
  "trigonometry",
  "calculus",
  "probability",
  "statistics",
  "combinator",
  "number",
  "matrix",
  "vector",
  "derivative",
  "integral",
  "limit",
  "equation",
  "function",
  "sequence",
  "series",
  "discrete",
  "graph",
  "optimization",
  "analysis",
  "theorem",
  "proof",
  "linear",
  "vector",
  "matrix",
  "topology",
  "measure",
];