import React from "react";
import { Box, Paper, Typography, Divider } from "@mui/material";

/**
 * AI Transparency / How Our AI Works / Content Policy / Powered by OpenAI
 * Useful to show on landing pages, about pages, and exam pages.
 */
export default function AITransparency(): JSX.Element {
  return (
    <Box sx={{ mt: 4, mb: 4 }}>
      <Paper elevation={1} sx={{ p: 2, borderRadius: 2 }}>
        <Typography variant="h6" sx={{ fontWeight: 800, mb: 1 }}>
          How Our AI Works
        </Typography>

        <Typography variant="body2" paragraph>
          Our artificial intelligence analyzes your answers, identifies strong and weak areas, and automatically generates new questions at an appropriate difficulty level. The system creates explanations, hints, and personalized recommendations to help you understand the material and prepare more efficiently.
        </Typography>

        <Typography variant="body2" paragraph>
          The platform does not use any official exam materials. All questions are generated by AI based on general testing principles and the typical structure of exams such as SAT and ACT.
        </Typography>

        <Typography variant="body2" paragraph>
          The AI operates in real time by:
        </Typography>
        <Typography variant="body2" component="div" sx={{ pl: 2 }}>
          <ul>
            <li>evaluating each of your responses;</li>
            <li>selecting training examples;</li>
            <li>adjusting difficulty;</li>
            <li>creating a personalized learning path.</li>
          </ul>
        </Typography>

        <Divider sx={{ my: 1 }} />

        <Typography variant="h6" sx={{ fontWeight: 800, mb: 1 }}>
          AI Content Policy
        </Typography>

        <Typography variant="body2" paragraph>
          All questions, explanations, and tasks are generated using artificial intelligence technologies. The materials are not official exam questions and are intended solely for practice and skill development. We comply with OpenAI usage policies and ensure that all generated content:
        </Typography>

        <Typography variant="body2" component="div" sx={{ pl: 2 }}>
          <ul>
            <li>does not copy protected or licensed materials;</li>
            <li>matches the approximate difficulty of the exam;</li>
            <li>is educational and helpful;</li>
            <li>does not mislead users about the origin of the questions.</li>
          </ul>
        </Typography>

        <Divider sx={{ my: 1 }} />

        <Typography variant="h6" sx={{ fontWeight: 800, mb: 1 }}>
          Powered by OpenAI
        </Typography>

        <Typography variant="body2">
          Our learning platform uses OpenAI technologies to generate questions, explanations, and performance analysis. The model helps create personalized tasks and recommendations, making the preparation process more accurate and adaptive.
        </Typography>
      </Paper>
    </Box>
  );
}