import ResponsiveMotion from "./ResponsiveMotion";
import styles from "../styles/HowItWorks.module.css";

const steps = [
  {
    title: "Take a Smart Test",
    desc: "Start a test generated by AI — every question is fresh, challenging, and designed to match your skill level and topic of choice.",
    icon: "/images/how1.png",
  },
  {
    title: "Get Instant Explanation",
    desc: "See clear, step-by-step explanations immediately after each question to understand mistakes and strengthen your knowledge.",
    icon: "/images/how2.png",
  },
  {
    title: "Track and Improve",
    desc: "Monitor your progress with real-time analytics that highlight your growth and guide you toward better exam performance.",
    icon: "/images/how3.png",
  },
];

export default function HowItWorks() {
  return (
    <ResponsiveMotion
      as="section"
      className={styles.howItWorks}
      initial={{ opacity: 0, y: 60 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.8, delay: 0.3, ease: [0.39, 0.58, 0.57, 1] }}
      id="how-it-works"
    >
      <h2 className={styles.title}>How It Works</h2>
      <div className={styles.timeline}>
        {steps.map((step, idx) => (
          <div className={styles.step} key={step.title}>
            <img src={step.icon} alt={step.title} className={styles.icon} />
            <div>
              <h3 className={styles.stepTitle}>{step.title}</h3>
              <p className={styles.stepDesc}>{step.desc}</p>
            </div>
            {idx < steps.length - 1 && <div className={styles.arrow}>→</div>}
          </div>
        ))}
      </div>
      <div className={styles.demo}>
        <video
          src="/images/demo.mp4"
          className={styles.demoImg}
          autoPlay
          loop
          muted
          playsInline
          width={800}
          height={450}
          poster=""
          aria-label="Demo of platform"
        />
      </div>
    </ResponsiveMotion>
  );
}