import React from "react";
import { Box, Typography, Paper } from "@mui/material";

/**
 * Legal & Content Disclaimer block
 * Place this prominently on exam landing pages (SAT/ACT) and on footer/registration flows.
 */
export default function LegalDisclaimer(): JSX.Element {
  return (
    <Box sx={{ mt: 4, mb: 4 }}>
      <Paper elevation={1} sx={{ p: 2, borderRadius: 2 }}>
        <Typography variant="h6" sx={{ fontWeight: 800, mb: 1 }}>
          Content and Exam Disclaimer
        </Typography>

        <Typography variant="body2" paragraph>
          Braini-HI CBT Platform is not an official product of, nor is it affiliated with, College Board, ACT, ETS, AST, or any other exam-administering organization. All practice questions, explanations, and tasks are generated using artificial intelligence technology and are simulations, not official exam materials.
        </Typography>

        <Typography variant="body2" paragraph>
          The AI-generated content is intended for practice and educational purposes only and does not represent exact replicas of real exam questions. Exam names (such as “SAT,” “ACT,” and “AST”) are used solely to describe the style and format of the practice materials.
        </Typography>

        <Typography variant="body2">
          By using this platform, the user acknowledges that the service provides educational content generated by AI and that the platform is not responsible for the outcomes of any official examinations.
        </Typography>
      </Paper>
    </Box>
  );
}