import Header from "../components/Header";
import Footer from "../components/Footer";
import Testimonial from "../components/Testimonials";
import FeatureGrid from "../components/About/FeatureGrid";
import ResponsiveMotion from "../components/ResponsiveMotion"; // <-- import the wrapper
import styles from "../styles/AboutPage.module.css";

export default function About() {
  return (
    <>
      <Header />
      <ResponsiveMotion as="main" className={styles.main}>
        {/* Hero Section */}
        <section className={styles.hero}>
          <div className={styles.heroOverlay}>
            <h1 className={styles.heroHeader}>
              Empowering Students to Excel in Mathematics with AI
            </h1>
            <p className={styles.heroSubtext}>
              We’re building an intelligent platform that helps students practice smarter, understand deeply, and achieve higher scores — powered by the latest in neural network technology.
            </p>
          </div>
          <div className={styles.heroBar}>
            <span className={styles.heroBarText}>About Brainihi.com</span>
          </div>
        </section>

        {/* Breadcrumb */}
        <div className={styles.breadcrumb}>
          | About Brainihi.com
        </div>

        {/* Feature Grid Section */}
        <FeatureGrid />

        {/* Our Mission Section */}
        <section className={styles.section}>
          <h2 className={styles.sectionTitle}>Our Mission</h2>
          <p className={styles.sectionText}>
            At <b>Brainihi.com</b>, our mission is to make mathematics preparation accessible, intelligent, and personalized.
            We believe learning math shouldn’t feel overwhelming — our AI generates custom tests, answers, and explanations so every student can study effectively at their own pace.
          </p>
        </section>

        {/* How It Works Section */}
        <section className={styles.howItWorks}>
          <h2 className={styles.sectionTitle}>How It Works</h2>
          <div className={styles.howGrid}>
            <div className={styles.howItem}>
              <img src="/images/how1.png" alt="Smart Test Creation" className={styles.howIcon} />
              <h3 className={styles.howHeader}>Smart Test Creation</h3>
              <p className={styles.howDesc}>The system generates new questions every time you practice.</p>
            </div>
            <div className={styles.howItem}>
              <img src="/images/how2.png" alt="AI-Powered Explanations" className={styles.howIcon} />
              <h3 className={styles.howHeader}>AI-Powered Explanations</h3>
              <p className={styles.howDesc}>Understand each step through detailed reasoning generated by neural networks.</p>
            </div>
            <div className={styles.howItem}>
              <img src="/images/how3.png" alt="Performance Tracking" className={styles.howIcon} />
              <h3 className={styles.howHeader}>Performance Tracking</h3>
              <p className={styles.howDesc}>Instantly view your results and areas for improvement.</p>
            </div>
          </div>
        </section>

        {/* Our Story Section */}
        <section className={styles.section}>
          <h2 className={styles.sectionTitle}>Our Story</h2>
          <p className={styles.sectionText}>
            The idea for <b>Brainihi.com</b> was born from a simple goal — to make learning mathematics adaptive and engaging. Our team of educators and AI developers joined forces to create a tool that mimics real tutoring, combining smart automation with clear explanations.
          </p>
        </section>

        {/* Testimonials Section */}
        <section className={styles.testimonialSection}>
          <Testimonial />
        </section>
      </ResponsiveMotion>
      <Footer />
    </>
  );
}