import Head from "next/head";
import Header from "../components/Header";
import AITransparency from "../components/AITransparency";
import LegalDisclaimer from "../components/LegalDisclaimer";
import StickyNotice from "../components/StickyNotice";
import layout from "../styles/Layout.module.css";
import { Box, Container, Typography, Paper } from "@mui/material";

/**
 * "How Our AI Works" — minimalist landing page.
 * Adds id="content-policy" to the content policy heading so footer Learn more scrolls here.
 */

export default function HowItWorksPage(): JSX.Element {
  const poweredText =
    "Powered by OpenAI — our platform uses OpenAI technologies to generate questions, explanations, and performance analysis. OpenAI provides the underlying models; BrainiHi configures prompts, validation and quality controls to produce safe, educational content.";

  return (
    <>
      <Head>
        <title>How Our AI Works — BrainiHi</title>
        <meta
          name="description"
          content="How BrainiHi's AI generates practice questions, adapts difficulty, and creates personalized study paths. Transparency, content policy, and powered-by information."
        />
      </Head>

      <Header />

      <main aria-labelledby="how-our-ai-heading" style={{ padding: "48px 0 140px" }}>
        <Container maxWidth="md" className={layout.container}>
          <Box sx={{ maxWidth: 880, margin: "0 auto" }}>
            {/* Hero / Intro */}
            <header style={{ marginBottom: 24 }}>
              <Typography id="how-our-ai-heading" component="h1" variant="h4" sx={{ fontWeight: 800, mb: 1 }}>
                How Our AI Works
              </Typography>

              <Typography variant="body1" color="text.secondary" sx={{ mb: 2, lineHeight: 1.6 }}>
                Our artificial intelligence analyzes your answers, identifies strong and weak areas, and automatically generates new questions at an appropriate difficulty level.
                The system creates explanations, hints, and personalized recommendations to help you understand the material and prepare more efficiently.
              </Typography>

              <Typography variant="body1" color="text.secondary" sx={{ mb: 2, lineHeight: 1.6 }}>
                The platform does not use any official exam materials. All questions are generated by AI based on general testing principles and the typical structure of exams such as SAT and ACT.
              </Typography>

              <Typography variant="body1" color="text.secondary" sx={{ mb: 1, fontWeight: 700 }}>
                In real time the AI:
              </Typography>
              <ul style={{ marginTop: 8, marginBottom: 18, color: "rgba(0,0,0,0.7)" }}>
                <li>evaluates each of your responses;</li>
                <li>selects targeted training examples;</li>
                <li>adjusts difficulty based on performance;</li>
                <li>creates a personalized learning path.</li>
              </ul>
            </header>

            {/* Content Generation Policy (concise, professional) */}
            <Paper elevation={0} sx={{ p: 3, mb: 3, borderRadius: 2, border: "1px solid rgba(0,0,0,0.06)" }}>
              <Typography variant="h6" id="content-policy" sx={{ fontWeight: 800, mb: 1 }}>
                Content generation policy
              </Typography>

              <Typography variant="body2" color="text.secondary" sx={{ mb: 1 }}>
                All practice questions, explanations and tasks on BrainiHi are generated using artificial intelligence and are intended for practice and learning only. We follow strict safeguards to ensure:
              </Typography>

              <ul style={{ margin: "8px 0 12px 1rem", color: "rgba(0,0,0,0.7)" }}>
                <li>Questions do not copy protected or licensed exam materials.</li>
                <li>Each item follows a consistent schema for tracking, analytics and validation.</li>
                <li>Model prompts and responses are logged for quality review and debugging.</li>
                <li>We validate generated items and retry generation when outputs do not meet schema requirements.</li>
                <li>Duplicate and plagiarism checks are performed to reduce overlap with other items.</li>
              </ul>

              <Typography variant="body2" color="text.secondary">
                By using BrainiHi you acknowledge that content is AI-generated and provided for educational practice, not as official exam material.
              </Typography>
            </Paper>

            {/* AITransparency component (reused block with How Our AI Works, Content Policy, Powered by OpenAI) */}
            <AITransparency />

            {/* Small powered-by note (non-sticky) kept in content for SEO and screen readers */}
            <Box sx={{ mt: 2, mb: 3 }}>
              <Typography variant="caption" color="text.secondary">
                {poweredText}
              </Typography>
            </Box>

            {/* Legal disclaimer (keeps compliance visible near CTA) */}
            <LegalDisclaimer />
          </Box>
        </Container>
      </main>

      {/* Sticky notice pinned above footer. Dismiss persists permanently by default.
          If you prefer temporary dismissal (e.g., 1 day), pass persistMinutes={1440}. */}
      <StickyNotice text={poweredText} />

    </>
  );
}