import React from "react";
import layout from "../styles/Layout.module.css";

export default function Terms(): JSX.Element {
  return (
    <main className={layout.contentInner} style={{ padding: "40px 20px" }}>
      <article>
        <h1>Terms of Service — BrainiHi</h1>
        <p><strong>Last updated:</strong> October 2025</p>

        <p>Welcome to BrainiHi. By using BrainiHi.com you agree to the following terms.</p>

        <h2>1. The service</h2>
        <p>
          BrainiHi is an educational platform offering AI‑generated math tests and AI‑powered explanations.
          We may update, modify, or remove features at any time.
        </p>

        <h2>2. Eligibility</h2>
        <p>To use BrainiHi you must be at least 13 years old and legally capable of entering a contract.</p>
        <p>If you are under 18, a parent or guardian must consent to your use.</p>

        <h2>3. Account rules</h2>
        <ul>
          <li>Provide accurate account information.</li>
          <li>Keep your login secure and do not share credentials.</li>
          <li>Do not misuse the service or attempt to reverse engineer it.</li>
        </ul>
        <p>We may suspend or terminate accounts for misuse, fraud, or harmful behavior.</p>

        <h2>4. Payments & subscriptions</h2>
        <p>Payments are processed by Paddle. Billing and refund terms are presented at checkout and are
           subject to Paddle's policies and applicable local laws.</p>

        <h2>5. Intellectual property</h2>
        <p>
          All content on BrainiHi is protected by copyright. You may use content for personal educational
          purposes only. You may not copy, resell, or modify service content or attempt to reverse‑engineer
          the software.
        </p>

        <h2>6. AI disclaimer</h2>
        <p>
          Explanations are generated by AI. While we aim for useful, accurate explanations, we do not
          guarantee accuracy or suitability for official exam grading. Use AI-generated material at your
          own discretion.
        </p>

        <h2>7. Limitations of liability</h2>
        <p>
          BrainiHi is not responsible for exam results, loss of data, or service interruptions. Our
          maximum liability is limited to fees paid by you in the last 12 months to the extent permitted
          by law.
        </p>

        <h2>8. Termination</h2>
        <p>You may delete your account at any time. We may terminate accounts that violate these terms.</p>

        <h2>9. Governing law</h2>
        <p>These Terms are governed by the laws of the Republic of Kazakhstan. Disputes will be resolved in Kazakhstani courts.</p>

        <h2>10. Contact</h2>
        <p>For questions or notices: <a href="mailto:support@brainihi.com">support@brainihi.com</a></p>
      </article>
    </main>
  );
}